require("dotenv").config();
const express = require("express");
const http = require("http");
const { Server } = require("socket.io");
const { Pool } = require("pg");
const cors = require("cors");

const app = express();
const server = http.createServer(app);

const { exec } = require("child_process");
const simpleGit = require("simple-git");
const path = require("path");
const fs = require("fs");

const { Octokit } = require("@octokit/rest");
const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });

const git = simpleGit(path.join(__dirname, "../apps/course-assistant")); // Path to App B folder

// 1. Configure Middleware
app.use(cors());
app.use(express.json());

// 2. PostgreSQL Connection Configuration
const pool = new Pool({
  user: process.env.DB_USER,
  host: process.env.DB_HOST,
  database: process.env.DB_NAME,
  password: process.env.DB_PASSWORD,
  port: process.env.DB_PORT,
});

// Test DB Connection
pool.connect((err) => {
  if (err) {
    console.error("❌ Database connection error", err.stack);
  } else {
    console.log("✅ Connected to PostgreSQL");
  }
});

// 3. Socket.io Setup
const io = new Server(server, {
  cors: {
    origin: ["http://localhost:5173", "http://localhost:3001"], // App A and App B ports
    methods: ["GET", "POST"],
  },
});

io.on("connection", (socket) => {
  console.log(`📡 User connected: ${socket.id}`);

  socket.on("disconnect", () => {
    console.log("User disconnected");
  });
});

// 4. The "Save and Emit" Route
app.post("/save-code", async (req, res) => {
  const { filename, content } = req.body;

  try {
    // Insert into Postgres
    const query =
      "INSERT INTO code_snippets (filename, content) VALUES ($1, $2) RETURNING *";
    const values = [filename, content];
    const result = await pool.query(query, values);

    const savedSnippet = result.rows[0];

    // Emit the new data to all connected clients (App B will catch this)
    io.emit("new-code-arrival", savedSnippet);

    res.status(201).json({
      message: "Snippet saved and broadcasted!",
      data: savedSnippet,
    });
  } catch (err) {
    console.error("Error saving to DB:", err);
    res.status(500).json({ error: "Internal Server Error" });
  }
});

// 5. Optional: Get all snippets (for App B initialization)
app.get("/snippets", async (req, res) => {
  try {
    const result = await pool.query(
      "SELECT * FROM code_snippets ORDER BY created_at DESC",
    );
    res.json(result.rows);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

const PORT = 4000;
server.listen(PORT, () => {
  console.log(`🚀 Server running on http://localhost:${PORT}`);
});

app.post("/run-pipeline", async (req, res) => {
  const { filename, content } = req.body;

  try {
    // STEP 1: COMPILATION CHECK (LINTING)
    // We'll use a simple regex check or try to write it to a temp file
    console.log("Stage 1: Linting...");
    io.emit("pipeline-log", "🔍 Linting code for syntax errors...");

    if (content.includes("import") && !content.includes("from")) {
      throw new Error("Syntax Error: Incomplete import statement.");
    }

    // STAGE 1: Security & Tests
    io.emit("pipeline-update", "🛡️ Running security scans...");
    securityCheck(content);

    io.emit("pipeline-update", "🧪 Running unit tests...");
    runUnitTests(content);

    // STAGE 2: Git Branching
    const branchName = `sync-${Date.now()}`;
    io.emit("pipeline-update", `🌿 Creating branch: ${branchName}...`);
    await git.checkout("main");
    await git.pull("origin", "main");

    await git.checkoutLocalBranch(branchName);

    // --- DIRECTORY GUARD ---
    // This ensures the components/ folder exists before we write the file
    const targetDir = path.join(
      __dirname,
      "../apps/course-assistant/src/components",
    );

    if (!fs.existsSync(targetDir)) {
      console.log(`📂 Creating missing directory: ${targetDir}`);
      io.emit("pipeline-update", "📂 Creating missing components directory...");
      fs.mkdirSync(targetDir, { recursive: true });
    }
    const filePath = path.join(
      __dirname,
      `../apps/course-assistant/src/components/${filename}`,
    );
    fs.writeFileSync(filePath, content);

    await git.add("./*");

    const status = await git.status();
    if (status.staged.length === 0) {
      throw new Error(
        "No changes detected. The code is identical to what is already on GitHub.",
      );
    }

    await git.commit(`New Component: ${filename}`);
    await git.push("origin", branchName);

    // STAGE 3: Open Pull Request
    io.emit("pipeline-update", "📂 Opening Pull Request on GitHub...");
    const pr = await octokit.pulls.create({
      owner: "Syu125",
      repo: "integration-test",
      title: `Merge New Component: ${filename}`,
      head: branchName,
      base: "main",
      body: "This PR was automatically generated by the App A Pipeline after passing security and unit tests.",
    });

    io.emit("pipeline-update", `✅ PR Created: ${pr.data.html_url}`);

    // Switch back to main so the local repo stays clean
    await git.checkout("main");

    res.json({ prUrl: pr.data.html_url });
  } catch (err) {
    console.error(err);
    io.emit("pipeline-log", `❌ Error: ${err.message}`);
    res.status(500).json({ error: err.message });
  }
});

const securityCheck = (code) => {
  const forbidden = [
    "eval",
    "process",
    "child_process",
    "localStorage",
    "cookie",
  ];
  for (const word of forbidden) {
    if (code.includes(word))
      throw new Error(`Security Violation: Found forbidden keyword "${word}"`);
  }
  return true;
};

// Simple unit test simulation (You can eventually plug in Vitest here)
const runUnitTests = (code) => {
  if (code.length < 10)
    throw new Error("Unit Test Failed: Component is too small/empty.");
  if (!code.includes("return"))
    throw new Error("Unit Test Failed: Component has no return statement.");
  return true;
};
